### ISSUE TITLE
docker installed promcord process keeps restarting 

### ISSUE THREAD

**Issue by dmamalis** [nimarion/promcord#151]
## Bug Report
promcord docker process keeps restarting. Not sure if this is a bug or a misconfiguration of the bot on our server.
```
18:47:31.632 [main] INFO  de.biosphere.promcord.Promcord - Starting promcord
18:47:31.702 [main] INFO  de.biosphere.promcord.Configuration - Configuration loaded!
18:47:44.083 [main] ERROR de.biosphere.promcord.Promcord - Encountered exception while initializing JDA!
18:47:44.102 [main] ERROR de.biosphere.promcord.Promcord - Encountered exception while initializing the bot!
java.lang.IllegalStateException: Could not acquire lock in a reasonable timeframe! (10 seconds)
        at net.dv8tion.jda.api.utils.MiscUtil.tryLock(MiscUtil.java:164)
        at net.dv8tion.jda.api.utils.MiscUtil.locked(MiscUtil.java:126)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter.stop(BotRateLimiter.java:169)
        at net.dv8tion.jda.internal.requests.Requester.stop(Requester.java:321)
        at net.dv8tion.jda.internal.JDAImpl.shutdownInternals(JDAImpl.java:701)
        at net.dv8tion.jda.internal.JDAImpl.shutdown(JDAImpl.java:682)
        at net.dv8tion.jda.internal.JDAImpl.shutdownNow(JDAImpl.java:671)
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:360)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:281)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1929)
        at de.biosphere.promcord.Promcord.initializeJDA(Promcord.java:56)
        at de.biosphere.promcord.Promcord.<init>(Promcord.java:29)
        at de.biosphere.promcord.Promcord.main(Promcord.java:72)
18:47:46,779 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:47:46,785 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
18:47:46,793 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/promcord.jar!/logback.xml]
18:47:46,856 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3d8314f0 - URL [jar:file:/promcord.jar!/logback.xml] is not of type file
18:47:47,227 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
18:47:47,248 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.dv8tion.jda] to ERROR
18:47:47,248 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:47:47,267 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Console]
18:47:47,308 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:47:47,603 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [io.sentry.logback.SentryAppender]
18:47:47,777 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Sentry]
18:47:47,807 |-WARN in io.sentry.logback.SentryAppender[Sentry] - Failed to init Sentry during appender initialization: DSN is required. Use empty string to disable SDK.
18:47:47,807 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
18:47:47,807 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Console] to Logger[ROOT]
18:47:47,809 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Sentry] to Logger[ROOT]
18:47:47,809 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
18:47:47,810 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2df32bf7 - Registering current configuration as safe fallback point

```

**Comment by mazzma12** [comment]
same here with docker-compose 1.29.2

```
10:37:28,235 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:37:28,237 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:37:28,238 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/promcord.jar!/logback.xml]
10:37:28,257 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3d8314f0 - URL [jar:file:/promcord.jar!/logback.xml] is not of type file
10:37:28,353 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:37:28,357 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.dv8tion.jda] to ERROR
10:37:28,358 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:37:28,362 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Console]
10:37:28,371 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] pr

10:37:28,461 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [io.sentry.logback.SentryAppender]
10:37:28,547 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Sentry]
10:37:28,563 |-WARN in io.sentry.logback.SentryAppender[Sentry] - Failed to init Sentry during appender initialization: DSN is required. Use empty string to disable SDK.
10:37:28,563 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
10:37:28,563 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Console] to Logger[ROOT]
10:37:28,563 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Sentry] to Logger[ROOT]
10:37:28,563 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:37:28,564 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2df32bf7 - Registering current configuration as safe fallback point

```

**Comment by DMTryptamines** [comment]
I'm also getting this issue, any fix coming?

```
09:12:22.452 [main] INFO  de.biosphere.promcord.Promcord - Starting promcord
09:12:22.497 [main] INFO  de.biosphere.promcord.Configuration - Configuration loaded!
09:12:33.883 [main] ERROR de.biosphere.promcord.Promcord - Encountered exception while initializing JDA!
09:12:33.890 [main] ERROR de.biosphere.promcord.Promcord - Encountered exception while initializing the bot!
java.lang.IllegalStateException: Could not acquire lock in a reasonable timeframe! (10 seconds)
        at net.dv8tion.jda.api.utils.MiscUtil.tryLock(MiscUtil.java:164)
        at net.dv8tion.jda.api.utils.MiscUtil.locked(MiscUtil.java:126)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter.stop(BotRateLimiter.java:169)
        at net.dv8tion.jda.internal.requests.Requester.stop(Requester.java:321)
        at net.dv8tion.jda.internal.JDAImpl.shutdownInternals(JDAImpl.java:701)
        at net.dv8tion.jda.internal.JDAImpl.shutdown(JDAImpl.java:682)
        at net.dv8tion.jda.internal.JDAImpl.shutdownNow(JDAImpl.java:671)
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:360)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:281)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1929)
        at de.biosphere.promcord.Promcord.initializeJDA(Promcord.java:56)
        at de.biosphere.promcord.Promcord.<init>(Promcord.java:29)
        at de.biosphere.promcord.Promcord.main(Promcord.java:72)
```

**Comment by DMTryptamines** [comment]
Right after porting the above I figured out the issue. I had to set these settings and the block of text went away, still get the `Could NOT find resource [logback-test.xml]` and `Could NOT find resource [logback.groovy]` errors though. You may only have to set on I'm not sure. 

![intents](https://user-images.githubusercontent.com/86132393/173800329-4ed939ea-d8ed-414e-957c-d681168f98ca.PNG)
